global using Xunit;
global using Serilog;
global using Microsoft.EntityFrameworkCore;
global using FastArchitecture.Handlers.Abstractions;
global using FastArchitecture.Infrastructure.Persistence;
global using FastArchitecture.UnitTests.Shared;
global using FastArchitecture.Handlers.Orders.Commands;
global using FastArchitecture.Handlers.Orders.Queries;
global using FastArchitecture.UnitTests.Factories;